FROM maven:3.9.6-eclipse-temurin-21 AS build
ARG SERVICE_DIR
WORKDIR /app
COPY ${SERVICE_DIR}/pom.xml .
COPY ${SERVICE_DIR}/src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
